/* App.svelte generated by Svelte v3.31.2 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "https://esm.sh/svelte/internal";

function create_fragment(ctx) {
	let p;

	return {
		c() {
			p = element("p");
			p.textContent = `${num + 9} klk popola`;
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

let num = 10;

function instance($$self) {
	
	return [];
}

class App extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

new App({ target: document.body });